[package]
name = "mpn_config"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[lib]
doc = false
doctest = false

[dependencies]
terminal_size = "0.3.0"
unindent = "0.2.3"
